apache:
  image: dockerizedrupal/apache-2.4:1.2.8
  hostname: apache
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - apache-data
  environment:
    - SERVER_NAME=localhost
    - DOCUMENT_ROOT=/apache/data
    - TIMEZONE=Etc/UTC
    - TIMEOUT=300
    - PROTOCOLS=https,http
    - INDEXES=Off
    - KERBEROS_DEFAULT_REALM=
    - KERBEROS_1_REALM=
    - KERBEROS_1_DOMAIN=
    - KERBEROS_1_KDC=
    - KERBEROS_1_ADMIN_SERVER=
    - HSTS=Off
    - HSTS_MAX_AGE=31536000
    - HSTS_PRELOAD=Off
    - HSTS_INCLUDE_SUBDOMAINS=Off
    - HTTP_BASIC_AUTH=Off
    - HTTP_BASIC_AUTH_USERNAME=container
    - HTTP_BASIC_AUTH_PASSWORD=
    - ESTEID=Off
    - ESTEID_CA_REVOCATION_LIST=Off
    - ESTEID_URL=
    - NO_GZIP=Off
    - CERTBOT=Off
    - CERTBOT_EMAIL=
    - PROXY=Off
    - PROXY_1_PASS=
    - PROXY_1_PASS_REVERSE=
    - USER_ID=
    - GROUP_ID=
apache-data:
  image: dockerizedrupal/apache-2.4:1.2.8
  hostname: apache-data
  entrypoint: ["/bin/echo", "Data-only container for Apache."]
  volumes:
    - /apache/data
    - /apache/ssl
